### ISSUE TITLE
Release new source packages

### ISSUE THREAD

**Issue by MichelZ** [morelinq/srcpkg#4]
It would be nice if source packages would update and kept in sync with the main development branch (e.g. same versions),

**Comment by atifaziz** [comment]
@MichelZ The source packages have become complicated to maintain going forward so I am not sure they will or can be kept in sync. The complication stems from the fact that we have been moving to embrace the latest C# features and the language itself is moving quicker with point releases. When delivering MoreLINQ as an assembly, the consuming project doesn't have to care what version of C# was used to develop MoreLINQ, but with the source packages, we'd need to stay compatible with some old C# version being used by some consuming project. This would tie our hands for a very long time for the main project only to benefit a few people using the source packages.

One way I see to keep the source packages in sync would be to maintain them by hand. Since most C# features up to now have been syntactic sugar, one would have to take a release's sources and lower them to an older C# syntax. I'm sure you'll agree, that's not a very appealing idea.

Projects wanting to bundle MoreLINQ internally have two alternative options:

- Use [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) if Git is being used as the project's VCS
- Use [ILMerge](https://github.com/Microsoft/ILMerge)

Do you see another way?

**Comment by atifaziz** [comment]
Closing as stale due to no further feedback/comment.
